---
- name: instal jkd11
  hosts: all
  tasks:
  - name: update latest software in the server
    ansible.buildin.yum:
      name: "*"
      state: latest
  - name: enable open jdk in amazon linux
    ansible.buildin.command: amazon-linux-extracs enable java-openjdk11
  - name:  instal the openjdk11
    ansible.buildin.yum:
      name: java-11-openjdk
      state: latest
